import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Activity, AlertTriangle, ArrowLeftRight, Bell, Boxes, ChartNoAxesColumn, Check, ChevronDown, ChevronRight, CircleHelp, ClipboardCheck, Download, LayoutDashboard, LogOut, Menu, Package, Plus, Search, Settings, SlidersHorizontal, Truck, Users, X } from 'lucide-react'

type User = { id: string; name: string; email: string; role: 'ADMIN' | 'EMPLOYEE'; businessId: string }
type Product = { id: string; sku: string; name: string; unit: string; quantity: number; minStock: number; price: number | string; category?: { name: string } | null; supplier?: { id: string; name: string } | null; supplierId?: string | null }
type Supplier = { id: string; name: string; email?: string; phone?: string; _count?: { products: number; requests: number } }
type Movement = { id: string; type: 'ENTRY' | 'EXIT' | 'ADJUSTMENT'; quantity: number; reason: string; createdAt: string; beforeQty: number; afterQty: number; product: Product; user: { name: string } }
type Alert = { id: string; status: 'OPEN' | 'ATTENDED'; createdAt: string; attendedAt?: string; falsePositive?: boolean; product: Product }
type RequestRow = { id: string; status: string; createdAt: string; receivedAt?: string; supplier: Supplier; items: { product: Product; quantity: number }[] }
type Metrics = { alertsAttendedWithin24hPercent: number|null; stockoutsAvoidedThisMonth: number; averageAlertResponseHours: number|null; inventoryAccuracyPercent: number|null; falsePositiveAlertPercent: number|null; openAlerts: number; products: number; movementsLast30Days: number; auditLinesLast30Days: number }
type TeamMember = { id:string; name:string; email:string; role:'ADMIN'|'EMPLOYEE'; createdAt:string }
type AuditLine = { id:string; accuracy:number }
type AuditRecord = { id:string; createdAt:string; user?:{name:string}; lines:AuditLine[] }
type RuntimeMetrics = { database:'ok'|'error'; databaseLatencyMs:number; databaseActiveConnections:number|null; databaseQueries:number; averageQueryLatencyMs:number; slowQueriesOver250ms:number; uptimeSeconds:number; averageLatencyMs:number; requestsPerSecond:number; errors5xx:number; errorRatePercent:number; processMemoryBytes:{rss:number}; hostMemory:{freeBytes:number}; cpuLoadAverage:number[]; gpu:string }
type Screen = 'Resumen'|'Productos'|'Movimientos'|'Proveedores'|'Alertas'|'Abastecimiento'|'Reportes'|'Equipo'
const money = (n: number|string) => Number(n).toLocaleString('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2})
const prettyDate = (s:string) => new Date(s).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})
let refreshInFlight:Promise<boolean>|null=null
function renewSession():Promise<boolean>{
  if(!refreshInFlight)refreshInFlight=fetch(`${import.meta.env.VITE_API_URL??''}/api/auth/refresh`,{method:'POST',credentials:'include'}).then(response=>response.ok).catch(()=>false).finally(()=>{refreshInFlight=null})
  return refreshInFlight
}
async function api<T=unknown>(path:string, init:RequestInit={}):Promise<T>{
  const url=`${import.meta.env.VITE_API_URL??''}${path}`
  const options:RequestInit={...init,credentials:'include',headers:{...(init.body?{'Content-Type':'application/json'}:{}),...init.headers}}
  let response=await fetch(url,options)
  if(response.status===401&&!['/api/auth/login','/api/auth/register','/api/auth/logout','/api/auth/refresh'].includes(path)){
    if(await renewSession())response=await fetch(url,options)
    else window.dispatchEvent(new Event('stockly:session-expired'))
  }
  if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||`Error ${response.status}`)}
  return response.status===204?undefined as T:response.json()
}
const links: {label:string;icon:typeof Package;items:Screen[]}[]=[{label:'Principal',icon:LayoutDashboard,items:['Resumen']},{label:'INVENTARIO',icon:Boxes,items:['Productos','Movimientos','Alertas']},{label:'GESTIÓN',icon:Truck,items:['Proveedores','Abastecimiento','Reportes','Equipo']}]
const linkIcon:Record<Screen,typeof Package>={Resumen:LayoutDashboard,Productos:Boxes,Movimientos:ArrowLeftRight,Proveedores:Truck,Alertas:Bell,Abastecimiento:ClipboardCheck,Reportes:ChartNoAxesColumn,Equipo:Users}

export default function App(){
  const [user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true),[toast,setToast]=useState('')
  useEffect(()=>{api<{user:User}>('/api/auth/me').then(x=>setUser(x.user)).catch(()=>{}).finally(()=>setChecking(false))},[])
  useEffect(()=>{const expire=()=>setUser(null);window.addEventListener('stockly:session-expired',expire);return()=>window.removeEventListener('stockly:session-expired',expire)},[])
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),3000)}
  if(checking)return <div className="loading-screen"><div className="brand-mark"><Boxes size={21}/></div><span>Preparando STOCKLY…</span></div>
  return <>{user?<Workspace user={user} onLogout={()=>{api('/api/auth/logout',{method:'POST'}).finally(()=>setUser(null))}} notify={notify}/>:<AuthScreen onLogin={setUser} notify={notify}/ >}{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</>
}

function AuthScreen({onLogin,notify}:{onLogin:(user:User)=>void;notify:(s:string)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('login'),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const result=await api<{user:User}>(`/api/auth/${mode==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify(mode==='login'?{email:data.email,password:data.password}:{business:data.business,name:data.name,email:data.email,password:data.password})});onLogin(result.user);notify(mode==='login'?'Sesión iniciada':'Negocio creado. ¡Bienvenido a STOCKLY!')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <div className="auth-screen"><div className="auth-brand"><div className="brand-mark"><Boxes size={21}/></div><span>stockly<span className="brand-period">.</span></span></div><div className="auth-card"><div className="auth-symbol"><Boxes size={22}/></div><p className="eyebrow">TU INVENTARIO, BAJO CONTROL</p><h1>{mode==='login'?'Qué gusto verte':'Empieza con STOCKLY'}</h1><p className="auth-copy">{mode==='login'?'Inicia sesión para continuar con tu negocio.':'Crea la cuenta administradora de tu negocio.'}</p><form onSubmit={submit}>{mode==='register'&&<><label>Nombre del negocio<input name="business" placeholder="Ej. Café de la Esquina" required minLength={2}/></label><label>Tu nombre<input name="name" placeholder="Nombre completo" required minLength={2}/></label></>}<label>Correo electrónico<input name="email" type="email" autoComplete="email" placeholder="tu@negocio.com" required/></label><label>Contraseña<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} placeholder={mode==='register'?'Mínimo 10 caracteres':'Tu contraseña'} minLength={mode==='register'?10:1} required/></label>{error&&<div className="form-error"><AlertTriangle size={15}/>{error}</div>}<button className="button button-primary auth-submit" disabled={busy}>{busy?'Un momento…':mode==='login'?'Iniciar sesión':'Crear mi cuenta'}</button></form><p className="auth-switch">{mode==='login'?'¿Primera vez aquí?':'¿Ya tienes cuenta?'} <button onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Crea tu negocio':'Inicia sesión'}</button></p><p className="auth-security">Tu espacio es privado y está aislado del resto de negocios.</p></div></div>
}

function Workspace({user,onLogout,notify}:{user:User;onLogout:()=>void;notify:(s:string)=>void}){
 const [screen,setScreen]=useState<Screen>('Resumen'),[products,setProducts]=useState<Product[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[movements,setMovements]=useState<Movement[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null),[team,setTeam]=useState<TeamMember[]>([]),[audits,setAudits]=useState<AuditRecord[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[modal,setModal]=useState<Screen|null>(null),[editingProduct,setEditingProduct]=useState<Product|null>(null),[editingSupplier,setEditingSupplier]=useState<Supplier|null>(null),[mobile,setMobile]=useState(false),[error,setError]=useState('')
 const refresh=useCallback(async()=>{setLoading(true);try{const [p,s,m,a,r,k,t,u]=await Promise.all([api<Product[]>('/api/products'),api<Supplier[]>('/api/suppliers'),api<Movement[]>('/api/movements'),api<Alert[]>('/api/alerts'),api<RequestRow[]>('/api/replenishments'),user.role==='ADMIN'?api<Metrics>('/api/reports/metrics'):Promise.resolve(null),user.role==='ADMIN'?api<TeamMember[]>('/api/users'):Promise.resolve([]),user.role==='ADMIN'?api<AuditRecord[]>('/api/audits'):Promise.resolve([])]);setProducts(p);setSuppliers(s);setMovements(m);setAlerts(a);setRequests(r);setMetrics(k);setTeam(t);setAudits(u)}catch(err){setError((err as Error).message)}finally{setLoading(false)}},[user.role])
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Carga la API al abrir el espacio y al cambiar de rol.
 useEffect(()=>{refresh()},[refresh])
 const isAdmin=user.role==='ADMIN',openAlerts=alerts.filter(a=>a.status==='OPEN')
 const visibleProducts=useMemo(()=>products.filter(p=>`${p.name} ${p.sku} ${p.category?.name||''}`.toLowerCase().includes(query.toLowerCase())&&(filter==='Todos'||(filter==='Stock bajo'?p.quantity<=p.minStock:p.category?.name===filter))),[products,query,filter])
 const act=async(path:string,method:string,body?:unknown,message='Cambios guardados')=>{setError('');try{await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});setModal(null);setEditingProduct(null);setEditingSupplier(null);await refresh();notify(message)}catch(err){setError((err as Error).message)}}
 const title=screen
 const exportCsv=()=>{const rows=[['SKU','Producto','Categoría','Existencias','Mínimo','Precio','Proveedor'],...products.map(p=>[p.sku,p.name,p.category?.name||'',p.quantity,p.minStock,p.price,p.supplier?.name||''])];const csv='\ufeff'+rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`stockly-inventario-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="app-shell"><aside className={`sidebar ${mobile?'sidebar-open':''}`}><div className="brand"><div className="brand-mark"><Boxes size={21} strokeWidth={2.5}/></div><span>stockly<span className="brand-period">.</span></span></div><button className="business-switch"><div className="business-avatar">{(products[0]?.category?.name||'S').slice(0,1)}</div><div className="business-info"><strong>{user.businessId?`Mi negocio`: 'STOCKLY'}</strong><small>{isAdmin?'Plan inicial · Admin':'Equipo · Empleado'}</small></div><ChevronDown size={15}/></button>{links.map(group=><div className="nav-group" key={group.label}><p className="nav-label">{group.label}</p>{group.items.filter(name=>user.role==="ADMIN"||(name!=="Reportes"&&name!=="Equipo")).map(name=>{const Icon=linkIcon[name];return <button key={name} onClick={()=>{setScreen(name);setMobile(false);setError('')}} className={`nav-item ${screen===name?'selected':''}`}><Icon size={18}/><span>{name}</span>{name==='Alertas'&&openAlerts.length>0&&<span className="nav-count">{openAlerts.length}</span>}</button>})}</div>)}<div className="sidebar-alert"><div className="alert-icon"><AlertTriangle size={17}/></div><div><strong>{openAlerts.length} alertas abiertas</strong><p>{openAlerts.length?'Revisa y atiende los productos con existencias críticas.':'Todo bien por ahora. Sigue registrando tus movimientos.'}</p><button onClick={()=>setScreen('Alertas')}>Ver alertas <span>→</span></button></div></div><div className="sidebar-bottom"><button className="nav-item" onClick={()=>setScreen('Reportes')}><Settings size={18}/><span>Métricas y monitoreo</span></button><button className="nav-item" onClick={()=>notify('Contacta al administrador de tu espacio')}><CircleHelp size={18}/><span>Centro de ayuda</span></button><div className="profile"><div className="profile-pic">{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="profile-info"><strong>{user.name}</strong><small>{isAdmin?'Administradora':'Empleado'}</small></div><button className="row-more" title="Cerrar sesión" onClick={onLogout}><LogOut size={17}/></button></div></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="Cerrar menú"/>}
 <main className="main-area"><header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setMobile(true)} aria-label="Abrir menú"><Menu size={20}/></button><div className="breadcrumbs"><span>STOCKLY</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="topbar-actions"><div className="today"><span className="live-dot"/> API conectada</div><button className="icon-button notification" aria-label="Ver alertas" onClick={()=>setScreen('Alertas')}><Bell size={18}/>{openAlerts.length>0&&<i/>}</button><div className="top-divider"/><button className="top-profile" onClick={onLogout}><span className="profile-pic small">{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><ChevronDown size={15}/></button></div></header>
 <div className="content"><div className="page-heading"><div><p className="eyebrow">{new Date().toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toLocaleUpperCase()} <span>·</span> {user.role==='ADMIN'?'ADMINISTRACIÓN':'OPERACIÓN'}</p><h1>{screen==='Resumen'?`Hola, ${user.name.split(' ')[0]}`:title}<span className="wave">{screen==='Resumen'?'✳':''}</span></h1><p className="heading-sub">{screen==='Resumen'?'Aquí tienes lo que está pasando con tu inventario.':'Consulta y administra la información de tu negocio.'}</p></div><div className="heading-actions">{screen==='Productos'&&<button className="button button-secondary" onClick={exportCsv}><Download size={16}/> Exportar CSV</button>}{screen==='Productos'&&isAdmin&&<button className="button button-primary" onClick={()=>setModal('Productos')}><Plus size={17}/>Nuevo producto</button>}{screen==='Movimientos'&&<button className="button button-primary" onClick={()=>setModal('Movimientos')}><Plus size={17}/>Registrar movimiento</button>}{screen==='Proveedores'&&isAdmin&&<button className="button button-primary" onClick={()=>setModal('Proveedores')}><Plus size={17}/>Nuevo proveedor</button>}{screen==='Abastecimiento'&&isAdmin&&<button className="button button-primary" onClick={()=>setModal('Abastecimiento')}><Plus size={17}/>Nueva solicitud</button>}{screen==='Reportes'&&<button className="button button-secondary" onClick={()=>setModal('Reportes')}><ClipboardCheck size={16}/>Auditoría física</button>}{screen==='Equipo'&&isAdmin&&<button className="button button-primary" onClick={()=>setModal('Equipo')}><Plus size={17}/>Añadir miembro</button>}</div></div>
 {error&&<div className="inline-error"><AlertTriangle size={16}/>{error}<button onClick={()=>setError('')}><X size={14}/></button></div>}
 {loading?<div className="loading-panel"><span className="spinner"/>Cargando los datos de tu negocio…</div>:<>
  {(screen==='Resumen'||screen==='Reportes')&&<MetricsOverview metrics={metrics} products={products} openAlerts={openAlerts}/>}{screen==='Resumen'&&<RecentPanels openAlerts={openAlerts} movements={movements} setScreen={setScreen}/ >}{screen==='Reportes'&&<ReportPanels audits={audits}/ >}
 {screen==='Productos'&&<Panel title="Catálogo de productos" subtitle={`${visibleProducts.length} productos de ${products.length}`}><div className="table-controls"><div className="search-box"><Search size={16}/><input placeholder="Buscar producto o SKU…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="filter-button" onClick={()=>setFilter(filter==='Todos'?'Stock bajo':'Todos')}><SlidersHorizontal size={15}/>{filter==='Todos'?'Filtrar':'Stock bajo'}</button><select className="category-select" value={filter==='Stock bajo'?'Todos':filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option>{[...new Set(products.map(p=>p.category?.name).filter((c):c is string=>Boolean(c)))].map(c=><option key={c}>{c}</option>)}</select></div><DataTable headers={['PRODUCTO / SKU','CATEGORÍA','EXISTENCIAS','STOCK MÍNIMO','PRECIO','ESTADO',...(isAdmin?['ACCIONES']:[])]} rows={visibleProducts.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small className="table-sub">{p.sku}</small></td><td><span className="category-tag">{p.category?.name||'Sin categoría'}</span></td><td className={p.quantity<=p.minStock?'qty-low':''}><strong>{p.quantity}</strong> {p.unit}</td><td>{p.minStock} {p.unit}</td><td>{money(p.price)}</td><td><span className={`status ${p.quantity<=p.minStock?'status-low':'status-ok'}`}><i/>{p.quantity<=p.minStock?'Stock bajo':'Disponible'}</span></td>{isAdmin&&<td className="action-cell"><button className="mini-action" onClick={()=>{setEditingProduct(p);setModal('Productos')}}>Editar</button><button className="mini-action" onClick={()=>window.confirm(`¿Desactivar ${p.name}? El historial se conservará.`)&&act(`/api/products/${p.id}`,'DELETE',undefined,'Producto desactivado')}>Desactivar</button></td>}</tr>)}/></Panel>}
 {screen==='Movimientos'&&<Panel title="Libro de movimientos" subtitle="Registro auditable de entradas, salidas y ajustes; el historial es inmutable"><MovementTable moves={movements}/></Panel>}
 {screen==='Proveedores'&&<Panel title="Directorio de proveedores" subtitle="Contactos vinculados a tus productos y compras"><DataTable headers={['PROVEEDOR','CORREO','TELÉFONO','PRODUCTOS','SOLICITUDES',...(isAdmin?['ACCIONES']:[])]} rows={suppliers.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.email||'—'}</td><td>{s.phone||'—'}</td><td>{s._count?.products??products.filter(p=>p.supplierId===s.id).length}</td><td>{s._count?.requests??requests.filter(r=>r.supplier.id===s.id).length}</td>{isAdmin&&<td className="action-cell"><button className="mini-action" onClick={()=>{setEditingSupplier(s);setModal('Proveedores')}}>Editar</button><button className="mini-action" onClick={()=>window.confirm(`¿Eliminar ${s.name}?`)&&act(`/api/suppliers/${s.id}`,'DELETE',undefined,'Proveedor eliminado')}>Eliminar</button></td>}</tr>)}/>{!suppliers.length&&<Empty title="Agrega tu primer proveedor" detail="Asocia proveedores a productos y solicitudes de reabastecimiento."/>}</Panel>}
 {screen==='Alertas'&&<Panel title="Alertas de stock mínimo" subtitle="Se generan al alcanzar o cruzar el mínimo. Atiéndelas para medir tiempos de respuesta"><DataTable headers={['PRODUCTO','STOCK','MÍNIMO','ESTADO','GENERADA','ACCIÓN']} rows={alerts.map(a=><tr key={a.id}><td><strong>{a.product.name}</strong><small className="table-sub">{a.product.sku}</small></td><td className={a.product.quantity<=a.product.minStock?'qty-low':''}>{a.product.quantity} {a.product.unit}</td><td>{a.product.minStock}</td><td><span className={`status ${a.status==='OPEN'?'status-low':'status-ok'}`}><i/>{a.status==='OPEN'?'Abierta':'Atendida'}{a.falsePositive?' · falso positivo':''}</span></td><td>{prettyDate(a.createdAt)}</td><td className="action-cell">{a.status==='OPEN'&&isAdmin&&<><button className="mini-action" onClick={()=>act(`/api/alerts/${a.id}/attend`,'PATCH',{falsePositive:false},'Alerta atendida')}>Atender</button><button className="mini-action" onClick={()=>act(`/api/alerts/${a.id}/attend`,'PATCH',{falsePositive:true},'Falso positivo registrado')}>Falso positivo</button><button className="mini-action" onClick={()=>{setScreen('Abastecimiento');setModal('Abastecimiento')}}>Reabastecer</button></>}</td></tr>)}/>{!alerts.length&&<Empty title="Aún no se generan alertas" detail="Cuando un producto llegue a su stock mínimo aparecerá aquí."/>}</Panel>}
 {screen==='Abastecimiento'&&<Panel title="Solicitudes de reabastecimiento" subtitle="Solicitudes vinculadas a un proveedor y un producto"><DataTable headers={['FOLIO','PROVEEDOR','PRODUCTOS','ESTADO','CREADA','ACCIONES']} rows={requests.map(r=><tr key={r.id}><td><strong>{r.id.slice(-7).toUpperCase()}</strong></td><td>{r.supplier.name}</td><td>{r.items.map(i=>`${i.product.name} × ${i.quantity}`).join(', ')}</td><td><span className={`status ${r.status==='RECEIVED'?'status-ok':r.status==='CANCELLED'?'status-low':'status-pending'}`}><i/>{r.status==='RECEIVED'?'Recibida':r.status==='SENT'?'Enviada':r.status==='CANCELLED'?'Cancelada':'Borrador'}</span></td><td>{prettyDate(r.createdAt)}</td><td className="action-cell">{isAdmin&&r.status==='DRAFT'&&<button className="mini-action" onClick={()=>act(`/api/replenishments/${r.id}/status`,'PATCH',{status:'SENT'},'Solicitud marcada como enviada')}>Marcar enviada</button>}{isAdmin&&['DRAFT','SENT'].includes(r.status)&&<button className="mini-action" onClick={()=>act(`/api/replenishments/${r.id}/status`,'PATCH',{status:'RECEIVED'},'Recepción registrada; existencias actualizadas')}>Recibir</button>}</td></tr>)}/>{!requests.length&&<Empty title="Sin solicitudes de compra" detail="Crea una solicitud desde una alerta o con el botón Nueva solicitud."/>}</Panel>}
 {screen==='Equipo'&&<Panel title="Equipo del negocio" subtitle="Usuarios y roles con acceso a este espacio"><DataTable headers={['NOMBRE','CORREO','ROL','DESDE']} rows={team.map(m=><tr key={m.id}><td><strong>{m.name}</strong></td><td>{m.email}</td><td><span className="category-tag">{m.role==='ADMIN'?'Administrador':'Empleado'}</span></td><td>{prettyDate(m.createdAt)}</td></tr>)}/></Panel>}
 </>}
 <footer className="footer"><span>© STOCKLY · Datos aislados por negocio.</span><span>¿Necesitas ayuda? <button onClick={()=>notify('Contacta al administrador del proyecto')}>Contáctanos</button></span></footer></div></main>
  {modal&&<Modal screen={modal} products={products} suppliers={suppliers} alerts={openAlerts} editingProduct={editingProduct} editingSupplier={editingSupplier} onClose={()=>{setModal(null);setEditingProduct(null);setEditingSupplier(null);setError('')}} onSubmit={act} error={error}/>}</div>
}

function Panel({title,subtitle,action,children}:{title:string;subtitle:string;action?:ReactNode;children:ReactNode}){return <section className="section-card inventory-card"><div className="section-head"><div><div className="section-title-line"><h2>{title}</h2></div><p>{subtitle}</p></div>{action}</div>{children}</section>}
function MetricsOverview({metrics,products,openAlerts}:{metrics:Metrics|null;products:Product[];openAlerts:Alert[]}){return <><section className="metrics"><Metric label="Productos registrados" value={String(metrics?.products??products.length).padStart(2,'0')} note="en tu catálogo" icon={<Package size={18}/>} tone="mint"/><Metric label="Unidades en inventario" value={products.reduce((n,p)=>n+p.quantity,0).toLocaleString('es-MX')} note="existencias registradas" icon={<Boxes size={18}/>} tone="lilac"/><Metric label="Alertas abiertas" value={String(metrics?.openAlerts??openAlerts.length).padStart(2,'0')} note="requieren seguimiento" icon={<AlertTriangle size={18}/>} tone="amber" warning/><Metric label="Movimientos · 30 días" value={String(metrics?.movementsLast30Days??0)} note="entradas, salidas y ajustes" icon={<Activity size={18}/>} tone="sky"/></section><div className="monitor-grid"><Metric label="Alertas atendidas en 24 h" value={metrics?.alertsAttendedWithin24hPercent==null?'—':`${metrics.alertsAttendedWithin24hPercent}%`} note="Meta: ≥ 90%" icon={<Bell size={17}/>} tone="mint"/><Metric label="Tiempo promedio de respuesta" value={metrics?.averageAlertResponseHours==null?'—':`${metrics.averageAlertResponseHours} h`} note="Meta en horario laboral: < 4 h" icon={<Activity size={17}/>} tone="sky"/><Metric label="Exactitud del inventario" value={metrics?.inventoryAccuracyPercent==null?'Sin auditorías':`${metrics.inventoryAccuracyPercent}%`} note={`Meta: ≥ 98% · ${metrics?.auditLinesLast30Days??0} productos auditados`} icon={<ClipboardCheck size={17}/>} tone="lilac"/><Metric label="Quiebres evitados este mes" value={String(metrics?.stockoutsAvoidedThisMonth??0)} note="Solicitudes recibidas con alerta" icon={<Check size={17}/>} tone="amber"/><Metric label="Falsos positivos de alertas" value={metrics?.falsePositiveAlertPercent==null?'—':`${metrics.falsePositiveAlertPercent}%`} note="Alertas atendidas sin necesidad de compra" icon={<SlidersHorizontal size={17}/>} tone="sky"/><Metric label="Productos bajo mínimo" value={String(openAlerts.length).padStart(2,'0')} note="alertas abiertas" icon={<AlertTriangle size={17}/>} tone="amber" warning/></div></>}
function RecentPanels({openAlerts,movements,setScreen}:{openAlerts:Alert[];movements:Movement[];setScreen:(s:Screen)=>void}){return <><Panel title="Productos que requieren atención" subtitle="Existencias iguales o inferiores al mínimo configurado" action={<button className="button button-quiet" onClick={()=>setScreen('Alertas')}>Ver alertas<ChevronRight size={15}/></button>}>{openAlerts.length?<DataTable headers={['PRODUCTO','SKU','EXISTENCIAS','MÍNIMO','ALERTA DESDE']} rows={openAlerts.slice(0,5).map(a=><tr key={a.id}><td><strong>{a.product.name}</strong></td><td>{a.product.sku}</td><td className="qty-low">{a.product.quantity} {a.product.unit}</td><td>{a.product.minStock}</td><td>{prettyDate(a.createdAt)}</td></tr>)}/>:<Empty title="No hay alertas abiertas" detail="Las existencias están por encima de sus mínimos configurados."/>}</Panel><Panel title="Movimientos recientes" subtitle="Últimas operaciones registradas" action={<button className="button button-quiet" onClick={()=>setScreen('Movimientos')}>Ver historial<ChevronRight size={15}/></button>}><MovementTable moves={movements.slice(0,5)}/></Panel></>}
function ReportPanels({audits}:{audits:AuditRecord[]}){return <><Panel title="Auditorías físicas" subtitle="Conteos de existencias realizados por el equipo"><DataTable headers={['FECHA','RESPONSABLE','PRODUCTOS CONTADOS','EXACTITUD']} rows={audits.map(a=><tr key={a.id}><td>{prettyDate(a.createdAt)}</td><td>{a.user?.name||'—'}</td><td>{a.lines.length}</td><td>{a.lines.length?`${(a.lines.reduce((n,l)=>n+l.accuracy,0)/a.lines.length*100).toFixed(1)}%`:'—'}</td></tr>)}/></Panel><Panel title="Monitoreo técnico" subtitle="Estado actual de la API y la base de datos"><Monitoring/></Panel></>}
function DataTable({headers,rows}:{headers:string[];rows:ReactNode[]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={headers.length} className="empty">Sin registros para mostrar.</td></tr>}</tbody></table></div>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty-state"><strong>{title}</strong><span>{detail}</span></div>}
function MovementTable({moves}:{moves:Movement[]}){return <DataTable headers={['PRODUCTO','TIPO','CANTIDAD','REGISTRÓ','FECHA','MOTIVO']} rows={moves.map(m=><tr key={m.id}><td><strong>{m.product.name}</strong><small className="table-sub">{m.product.sku}</small></td><td><span className={`movement-type ${m.type==='ENTRY'?'in':'out'}`}>{m.type==='ENTRY'?'Entrada':m.type==='EXIT'?'Salida':'Ajuste'}</span></td><td><strong>{m.type==='ENTRY'?'+':m.type==='EXIT'?'−':''}{m.quantity}</strong> {m.product.unit}</td><td>{m.user.name}</td><td>{prettyDate(m.createdAt)}</td><td>{m.reason}</td></tr>)}/>}
function Metric({label,value,note,icon,tone,warning=false}:{label:string;value:string;note:string;icon:ReactNode;tone:string;warning?:boolean}){return <div className="metric-card"><div className="metric-top"><span>{label}</span><span className={`metric-icon ${tone}`}>{icon}</span></div><div className="metric-value metric-small-value">{value}</div><div className={`metric-note ${warning?'warning-note':''}`}>{note}</div></div>}

function Modal({screen,products,suppliers,alerts,editingProduct,editingSupplier,onClose,onSubmit,error}:{screen:Screen;products:Product[];suppliers:Supplier[];alerts:Alert[];editingProduct:Product|null;editingSupplier:Supplier|null;onClose:()=>void;onSubmit:(path:string,method:string,body?:unknown,message?:string)=>Promise<void>;error:string}){
 const [busy,setBusy]=useState(false),[productId,setProductId]=useState(products[0]?.id||''),[supplierId,setSupplierId]=useState(suppliers[0]?.id||''),[alertId,setAlertId]=useState(alerts[0]?.id||''),[movementType,setMovementType]=useState('ENTRY')
 const title=screen==='Productos'?(editingProduct?'Editar producto':'Agregar producto'):screen==='Proveedores'?(editingSupplier?'Editar proveedor':'Nuevo proveedor'):screen==='Movimientos'?'Registrar movimiento':screen==='Abastecimiento'?'Crear solicitud':screen==='Equipo'?'Añadir miembro': 'Auditoría física'
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);try{
  if(screen==='Productos')await onSubmit(editingProduct?`/api/products/${editingProduct.id}`:'/api/products',editingProduct?'PATCH':'POST',{sku:data.get('sku'),name:data.get('name'),category:data.get('category'),supplierId:data.get('supplierId')||null,unit:data.get('unit'),quantity:Number(data.get('quantity')),minStock:Number(data.get('minStock')),price:Number(data.get('price'))},editingProduct?'Producto actualizado':'Producto agregado')
  if(screen==='Proveedores')await onSubmit(editingSupplier?`/api/suppliers/${editingSupplier.id}`:'/api/suppliers',editingSupplier?'PATCH':'POST',{name:data.get('name'),email:data.get('email'),phone:data.get('phone')},editingSupplier?'Proveedor actualizado':'Proveedor agregado')
  if(screen==='Movimientos')await onSubmit('/api/movements','POST',{productId:data.get('productId'),type:movementType,quantity:Number(data.get('quantity')),reason:data.get('reason')},'Movimiento registrado')
  if(screen==='Abastecimiento')await onSubmit('/api/replenishments','POST',{supplierId,alertId:alertId||undefined,notes:data.get('notes'),items:[{productId,quantity:Number(data.get('quantity'))}]},'Solicitud creada')
  if(screen==='Equipo')await onSubmit('/api/users','POST',{name:data.get('name'),email:data.get('email'),password:data.get('password'),role:data.get('role')},'Miembro agregado')
  if(screen==='Reportes')await onSubmit('/api/audits','POST',{items:products.map(p=>({productId:p.id,physicalQuantity:Number(data.get(`stock-${p.id}`))}))},'Auditoría registrada')
 }finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><span className="modal-icon"><Boxes size={19}/></span><div><h2>{title}</h2><p>Los cambios se guardan en la base de datos del negocio.</p></div></div><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={19}/></button></div><form onSubmit={submit}>
 {screen==='Productos'&&<><label>Nombre<input name="name" required minLength={2} placeholder="Ej. Café molido" defaultValue={editingProduct?.name}/></label><div className="form-row"><label>SKU<input name="sku" required placeholder="CAF-001" defaultValue={editingProduct?.sku}/></label><label>Categoría<input name="category" required placeholder="Abarrotes" defaultValue={editingProduct?.category?.name}/></label></div><div className="form-row"><label>Existencias<input name="quantity" type="number" min="0" defaultValue={editingProduct?.quantity??0} required/></label><label>Stock mínimo<input name="minStock" type="number" min="0" defaultValue={editingProduct?.minStock??5} required/></label></div><div className="form-row"><label>Precio unitario<input name="price" type="number" min="0" step="0.01" defaultValue={editingProduct?.price??0} required/></label><label>Unidad<input name="unit" defaultValue={editingProduct?.unit??'pz'} required/></label></div><label>Proveedor<select name="supplierId" defaultValue={editingProduct?.supplierId||''}><option value="">Sin proveedor</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label></>}
 {screen==='Proveedores'&&<><label>Nombre del proveedor<input name="name" required placeholder="Distribuidora…" defaultValue={editingSupplier?.name}/></label><div className="form-row"><label>Correo<input name="email" type="email" placeholder="compras@proveedor.com" defaultValue={editingSupplier?.email||''}/></label><label>Teléfono<input name="phone" placeholder="55 1234 5678" defaultValue={editingSupplier?.phone||''}/></label></div></>}
 {screen==='Movimientos'&&<><label>Producto<select name="productId" required>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.quantity} {p.unit}</option>)}</select></label><div className="form-row"><label>Tipo<select value={movementType} onChange={e=>setMovementType(e.target.value)}><option value="ENTRY">Entrada</option><option value="EXIT">Salida</option></select></label><label>Cantidad<input name="quantity" type="number" min="1" defaultValue="1" required/></label></div><label>Motivo<input name="reason" minLength={2} required placeholder="Compra a proveedor, venta, merma…"/></label></>}
 {screen==='Abastecimiento'&&<><label>Proveedor<select value={supplierId} onChange={e=>setSupplierId(e.target.value)} required>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Producto<select value={productId} onChange={e=>setProductId(e.target.value)} required>{products.map(p=><option key={p.id} value={p.id}>{p.name} · stock {p.quantity}</option>)}</select></label><div className="form-row"><label>Cantidad a solicitar<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Alerta vinculada<select value={alertId} onChange={e=>setAlertId(e.target.value)}><option value="">Ninguna</option>{alerts.filter(a=>a.product.id===productId).map(a=><option value={a.id} key={a.id}>{a.product.name}</option>)}</select></label></div><label>Notas<input name="notes" placeholder="Detalles para el proveedor"/></label></>}
 {screen==='Equipo'&&<><label>Nombre<input name="name" required minLength={2}/></label><label>Correo<input name="email" type="email" required/></label><label>Contraseña temporal<input name="password" type="password" minLength={10} required placeholder="Mínimo 10 caracteres"/></label><label>Rol<select name="role"><option value="EMPLOYEE">Empleado</option><option value="ADMIN">Administrador</option></select></label></>}
 {screen==='Reportes'&&<div className="audit-list">{products.map(p=><label key={p.id}>{p.name}<span>Sistema: {p.quantity} {p.unit}</span><input name={`stock-${p.id}`} type="number" min="0" defaultValue={p.quantity} required/></label>)}</div>}
 {error&&<div className="form-error"><AlertTriangle size={15}/>{error}</div>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancelar</button><button className="button button-primary" disabled={busy||((screen==='Abastecimiento')&&!suppliers.length)||((screen==='Movimientos'||screen==='Abastecimiento'||screen==='Reportes')&&!products.length)}>{busy?'Guardando…':screen==='Reportes'?'Guardar auditoría':title}</button></div>{screen==='Abastecimiento'&&!suppliers.length&&<span className="inline-hint">Primero registra al menos un proveedor.</span>}</form></div></div>
}

function Monitoring(){const [data,setData]=useState<RuntimeMetrics|null>(null),[error,setError]=useState('');useEffect(()=>{api<RuntimeMetrics>('/api/monitoring').then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'No se pudo cargar el monitoreo'))},[]);if(error)return <div className="monitor-note">No se pudo consultar el monitoreo: {error}</div>;if(!data)return <div className="monitor-note">Consultando métricas del servidor…</div>;return <div className="runtime-metrics"><div><span>Base de datos</span><strong className={data.database==='ok'?'good-text':'bad-text'}>{data.database==='ok'?'Conectada':'Sin conexión'} · {data.databaseLatencyMs} ms</strong></div><div><span>Conexiones activas (consulta PostgreSQL)</span><strong>{data.databaseActiveConnections??'No disponible'}</strong></div><div><span>Consultas registradas en este proceso</span><strong>{data.databaseQueries} · promedio {data.averageQueryLatencyMs} ms</strong></div><div><span>Consultas lentas (≥ 250 ms)</span><strong>{data.slowQueriesOver250ms}</strong></div><div><span>Tiempo activo</span><strong>{Math.floor(data.uptimeSeconds/60)} min</strong></div><div><span>Latencia promedio API</span><strong>{data.averageLatencyMs} ms</strong></div><div><span>Solicitudes / segundo (promedio del proceso)</span><strong>{data.requestsPerSecond}</strong></div><div><span>Errores HTTP 5xx</span><strong>{data.errorRatePercent}% · {data.errors5xx}</strong></div><div><span>Memoria del proceso / libre en host</span><strong>{Math.round(data.processMemoryBytes.rss/1048576)} / {Math.round(data.hostMemory.freeBytes/1073741824*10)/10} GB</strong></div><div><span>Carga CPU (1/5/15 min)</span><strong>{data.cpuLoadAverage.map(n=>n.toFixed(2)).join(' / ')}</strong></div><div><span>GPU</span><strong>{data.gpu}</strong></div></div>}

